JI-5465 state check for interactions
otacke/h5p-dictation pull request #108
Opened 2023-09-19 12:11 UTC by makmentins

These changes are aimed to accomplish basically the same thing that was done here https://github.com/otacke/h5p-sort-paragraphs/commit/03785a6d918d134ec429b8e9771a7fb2d5f5ca61, though I also needed to add the `resetAudio` calls to reset buttons' classes.

2023-09-19 14:13 UTC, otacke requested changes
Nice work. I just have some suggestions for improvements. Please let me know if I should do that myself or whether you're going to change those.

2023-09-19 14:13 UTC, otacke commented on src/scripts/h5p-dictation-sentence.js
> +      this.buttonPlayNormal.resetAudio();
I guess calling `resetAudio` could as well be done as part of `Button.reset` in general instead of calling after calling `Button.reset`, couldn't it?

2023-09-19 14:13 UTC, otacke commented on src/scripts/h5p-dictation.js
> +        return sentence.getCurrentState().buttonPlayNormal?.audio?.currentTime > 0
It's not necessary to go via `getCurrentState` to retrieve the buttons. They are exposed in the `Sentence` class.

I'd prefer to either access the buttons directly like `sentence.buttonPlayNormal` / `sentence.buttonPlaySlow` and to determine their state or to rather introduce an `isSomeButtonPlaying : boolean` function. Either way an `isPlaying : boolean` function in `Button` should be used.

2023-09-20 06:38 UTC, makmentins commented
Thanks, good points above - initially I just tried to find the fastest way to accomplish it while trying to just keep it understandable, but I do agree that your suggestions make sense and would improve the code, so the latest commit should address them.

2023-09-20 06:54 UTC, otacke commented
"Quicker, easier, more seductive." No need to tell me, I am tempted too often myself :-)

2023-09-20 06:55 UTC, merged