Add customizable wordSeparator and support alternatives with multiple words
otacke/h5p-dictation pull request #68
Opened 2021-05-13 21:46 UTC by tdjac0bs

This PR allow you to customize the word separator.

- This allows encoding the space placement in sentences, like "Test ?" or "Test?" 
- This also allows to encode alternatives with multiple words like "A-B|A - B"

Details covered in issue #67

2021-05-14 06:33 UTC, otacke requested changes
Thanks a lot!

I have not yet run the code but given it a first look. I spotted some things that I could probably fix myself quicker than explaining them here, but of course I hope that you will contribute more things to H5P in the future :-)

Whenever you change `semantics.json`, you will also have to update the translation files that H5P bases these on. They're found in https://github.com/otacke/h5p-dictation/tree/master/language If you don't do that, the H5P editor will get messed up for other languages than English. You do not have to translate these, of course, but you will have to put in the things that can actually be translated. Here that'd be the label and the description of your new field.

You can do that either manually - duh - or use the [H5P CLI tool](https://h5p.org/h5p-cli-guide). For this case, you would add `"state": "new"` to the field in semantics.json and then run `h5p update-translations h5p-dictation` from within the directory that contains the source folder. Other values for the state property would be "updated" which would overwrite all corresponding strings in the translation files and "removed" which would delete the strings for a field.

Could you please also take a look at the [H5P core team's coding guidelines](https://h5p.org/documentation/for-developers/coding-guidelines) and stick to these? The project contains a [configuration file for ESLint](https://github.com/otacke/h5p-dictation/blob/master/.eslintrc.json). Not sure if you can include ESLint in your editor (using it in atom) - but it really helps if the editor gives you a hint that something is odd. You can run it manually as well, of course, but I have never tried if that's possible with plugins like "jest" that I use here - but why wouldn't that work ...

I have also left a couple of comments for you. Would be great if you took care of those.

2021-05-14 06:33 UTC, otacke commented on src/scripts/h5p-dictation-sentence.js
> +      wordsInput = wordsInput.map( (word,i) => i==wordsInput.length-1 ? word : word + ' ');
The H5P core team favors template-strings nowadays as Babel takes care of those for IE11 even without a polyfill.

2021-05-14 06:33 UTC, otacke commented on semantics.json
> +      {
Could you please put this field after the `ignorePunctuation`? I try to keep these options in order of potential use, and using a different separator than a space is probably not the most likely one :-)

2021-05-17 19:50 UTC, tdjac0bs commented
Nice working on these changes.

2021-06-08 11:12 UTC, otacke commented
@tdjac0bs Sorry for not answering earlier, but since I am not a native English speaker, I may have misinterpreted your answer. I was under the impression that your answer meant something like "I'll gladly work on these changes", but re-reading it, it might also mean "Have fun with doing that yourself". Could you please let me know what interpretation is closer to what you meant?

2021-06-19 17:48 UTC, tdjac0bs commented
hello @otacke - you understood it correctly: "I'll gladly work on these changes"
working on this right now

2021-06-19 18:04 UTC, tdjac0bs commented on src/scripts/h5p-dictation-sentence.js
> +  static addSpaces(text, options = {}, wordSeparator=' ') {
I think I missed something here, in the function definition the second argument is an object, and it's used like an object: https://prnt.sc/15yoe3t

However, at function call it's sending the `autoSplit` variable directly: https://prnt.sc/15yoimk

Can you clarify it?

2021-06-19 18:52 UTC, otacke commented on src/scripts/h5p-dictation-sentence.js
> +  static addSpaces(text, options = {}, wordSeparator=' ') {
Hmm, that feels like a bug in my end then. Please just keep the `wordSeparator` argument separate then. I'll deal with it when I check the options object. Thanks for pointing that out!

2021-06-19 23:40 UTC, tdjac0bs commented on src/scripts/h5p-dictation-sentence.js
> +  static addSpaces(text, options = {}, wordSeparator=' ') {
cool, thank you!

2021-06-20 00:13 UTC, tdjac0bs commented
Hello, I've applied all suggested changes, but one error is happening.

Anything that I type in this new field is used as title for the accordion:

Text in new field:
![image](https://user-images.githubusercontent.com/2075267/122658408-3d83e480-d143-11eb-9ed7-278759523afe.png)

Accordion title:
![image](https://user-images.githubusercontent.com/2075267/122658404-34931300-d143-11eb-8c17-13f617b53806.png)

2021-06-20 10:08 UTC, otacke approved these changes
Something seems to have gone wrong with the translation files, but I'll fix that in a second myself.

The group label showing the symbols in the editor is not a bug, but a quirk of the H5P editor. It looks for the first (text) input field and uses its value as the group label. Don't know why, but that seems to be expected behavior.

2021-06-20 10:09 UTC, merged